const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const crypto = require("node:crypto");
const readline = require("node:readline/promises");

const ROOT = path.resolve(__dirname, "..");
const OUT = path.join(ROOT, ".env.lan");

function firstLanIp() {
  for (const entries of Object.values(os.networkInterfaces())) {
    for (const entry of entries || []) {
      if (entry.family === "IPv4" && !entry.internal) return entry.address;
    }
  }
  return "SERVER_IP";
}

function defaultWorkspacePath() {
  if (process.platform === "win32") {
    return path.join(os.homedir(), "Documents");
  }
  return "/srv/offline-ai/workspace";
}

function normalizeLmUrl(raw) {
  let value = String(raw || "").trim();
  if (!value) throw new Error("LM Studio URL vazia.");
  if (!/^https?:\/\//i.test(value)) value = `http://${value}`;
  const url = new URL(value);
  if (!url.port && (url.hostname === "localhost" || /^\d+\.\d+\.\d+\.\d+$/.test(url.hostname))) {
    url.port = "1234";
  }
  url.pathname = url.pathname.replace(/\/+$/, "") || "/v1";
  if (url.pathname === "/") url.pathname = "/v1";
  url.search = "";
  url.hash = "";
  return url;
}

function normalizeWorkspacePath(raw) {
  const value = String(raw || "").trim();
  if (!value) throw new Error("Workspace vazio.");
  const isWindowsAbs = /^[A-Za-z]:[\\/]/.test(value);
  if (!isWindowsAbs && !path.isAbsolute(value)) {
    throw new Error("Use um path absoluto para o workspace.");
  }
  return isWindowsAbs ? value.replace(/\\/g, "/") : value;
}

function envValue(value) {
  const s = String(value);
  if (/^[A-Za-z0-9_./:@,+-]+$/.test(s)) return s;
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function randomPassword() {
  return crypto.randomBytes(18).toString("base64url");
}

async function ask(rl, question, fallback) {
  const suffix = fallback ? ` [${fallback}]` : "";
  const answer = (await rl.question(`${question}${suffix}: `)).trim();
  return answer || fallback;
}

async function askYesNo(rl, question, fallback = true) {
  const hint = fallback ? "S/n" : "s/N";
  const answer = (await rl.question(`${question} [${hint}]: `)).trim().toLowerCase();
  if (!answer) return fallback;
  return answer === "s" || answer === "sim" || answer === "y" || answer === "yes";
}

async function main() {
  const lanIp = firstLanIp();
  const generatedPassword = randomPassword();
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });

  try {
    console.log("Offline AI Chat - assistente de configuracao LAN\n");
    console.log("Isto cria .env.lan para usar com docker-compose.lan.yml.");
    console.log("Nada e enviado para fora; as respostas ficam neste arquivo local.\n");

    if (fs.existsSync(OUT)) {
      const overwrite = await askYesNo(rl, ".env.lan ja existe. Sobrescrever?", false);
      if (!overwrite) {
        console.log("Cancelado. Mantive o .env.lan atual.");
        return;
      }
    }

    const appBind = await ask(rl, "Interface para expor o app na LAN", "0.0.0.0");
    const appPort = await ask(rl, "Porta do app", "8080");
    const appUser = await ask(rl, "Usuario de login", "offline-ai");
    const appPassword = await ask(rl, "Senha de login (Enter gera uma segura)", generatedPassword);

    let workspace;
    while (true) {
      try {
        workspace = normalizeWorkspacePath(await ask(rl, "Pasta compartilhada para RAG/workspace", defaultWorkspacePath()));
        if (!fs.existsSync(workspace.replace(/^([A-Za-z]):\//, "$1:\\"))) {
          const keep = await askYesNo(rl, "Essa pasta nao existe nesta maquina. Continuar mesmo assim?", false);
          if (!keep) continue;
        }
        break;
      } catch (err) {
        console.log(`Erro: ${err.message}`);
      }
    }

    let lmUrl;
    while (true) {
      try {
        lmUrl = normalizeLmUrl(await ask(rl, "URL do LM Studio", "http://192.168.1.50:1234/v1"));
        break;
      } catch (err) {
        console.log(`Erro: ${err.message}`);
      }
    }

    const ocrLangs = await ask(rl, "Idiomas OCR", "por+eng");
    const allowedLmHosts = lmUrl.host;

    const body = [
      "# Generated by npm run lan:setup",
      "# Do not commit this file. It contains the app login password.",
      "",
      `APP_BIND=${envValue(appBind)}`,
      `APP_PORT=${envValue(appPort)}`,
      "",
      `APP_AUTH_USER=${envValue(appUser)}`,
      `APP_AUTH_PASSWORD=${envValue(appPassword)}`,
      "",
      `LAN_WORKSPACE_HOST_PATH=${envValue(workspace)}`,
      `ALLOWED_LM_HOSTS=${envValue(allowedLmHosts)}`,
      "",
      `OCR_LANGS=${envValue(ocrLangs)}`,
      "MAX_FILE_BYTES=262144",
      "MAX_PDF_BYTES=33554432",
      "",
    ].join("\n");

    fs.writeFileSync(OUT, body, "utf8");

    console.log("\nConfiguracao LAN criada: .env.lan");
    console.log("\nProximos comandos:");
    console.log("  npm run lan:up");
    console.log("  npm run lan:logs");
    console.log("\nAbra no navegador:");
    console.log(`  http://${lanIp}:${appPort}`);
    console.log("\nLogin:");
    console.log(`  usuario: ${appUser}`);
    console.log(`  senha:   ${appPassword}`);
    console.log("\nNa UI, em Configuracoes -> Servidor, use:");
    console.log(`  ${lmUrl.toString().replace(/\/$/, "")}`);
  } finally {
    rl.close();
  }
}

main().catch((err) => {
  console.error(`Erro: ${err.message}`);
  process.exit(1);
});
